# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://travis-ci.org/
language: node_js
node_js:
  - "6"
  - "8"
install:
  - npm install
  - npm test
script:
  - npm run build
branches:
  only:
    - master